[flawfinder]
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "readlink"  # openmw isn't a privileged process
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "access"  # openmw isn't a privileged process
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "random"  # duh.
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "getenv"  # duh.
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "open" # openmw isn't a privileged process
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "char"  # too many false positives
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "read"  # too many false positives
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "snprintf"  # too many false positives
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "strlen"  # too many false positives
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "mkstemp"  # openmw doesn't run on old Unix systems
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "fopen"   # openmw isn't a privileged process
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "equal"  # only false positives, sigh
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "_snprintf"  # only false positives, sigh
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "printf"  # only false positives, sigh
	[[flawfinder.ruleset]]
		disable = true
		[flawfinder.ruleset.identifier]
			type = "flawfinder_func_name"
			value = "system"  # only false positives, sigh
